meta_product_name: "Awesomo"
meta_title: "Awesomo - A mini search engine for design assets"
meta_description: "Awesomo is a mini search engine to aid you in finding design assets."
meta_image: "Awesomo_Screenshot.png"
